Sprint7
ClevertecFrontendLab/KaPuTaH-UluTka pull request #5
Opened 2023-03-26 16:33 UTC by KaPuTaH-UluTka

2023-03-26 16:38 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 88%.
Общее количество тестов: 25.
Количество непройденных тестов: 3.
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679848727/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679848727/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679848727/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679848727/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679848727/19-profile-avatar-after.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679848727/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679848727/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679848727/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679848727/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679848727/24-1440-profile-empty-card.png)
***
**25-1440-profile-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679848727/25-1440-profile-history.png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 1440, 900 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679848727/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%201440,%20900%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 320, 240 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679848727/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20320,%20240%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 768, 576 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679848727/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20768,%20576%20(failed).png)

2023-03-26 16:58 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/24-1440-profile-empty-card.png)
***
**25-1440-profile-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/25-1440-profile-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/9-app%20-burger-menu-close-768px.png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 1440, 900 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%201440,%20900%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 320, 240 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20320,%20240%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 768, 576 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20768,%20576%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679849896/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 21:06 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 95%.
Общее количество тестов: 98.
Количество непройденных тестов: 4.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/24-1440-profile-empty-card.png)
***
**25-1440-profile-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/25-1440-profile-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/9-app%20-burger-menu-close-768px.png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 1440, 900 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%201440,%20900%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 320, 240 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20320,%20240%20(failed).png)
***
**Sprint 7 -- Profile functions tests -- profile form tests -- 768, 576 (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/Sprint%207%20--%20Profile%20functions%20tests%20--%20profile%20form%20tests%20--%20768,%20576%20(failed).png)
***
**Sprint 7 -- profile page -- screenshots (failed).png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679864797/Sprint%207%20--%20profile%20page%20--%20screenshots%20(failed).png)

2023-03-26 21:15 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 98.
Количество непройденных тестов: 0.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/24-1440-profile-empty-card.png)
***
**25-1440-profile-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/25-1440-profile-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679865329/9-app%20-burger-menu-close-768px.png)

2023-03-26 23:40 UTC, SergeyGlazun requested changes

2023-03-26 23:40 UTC, SergeyGlazun commented on cypress.config.ts
>  export default defineConfig({
![image](https://user-images.githubusercontent.com/70904466/227810984-4124186e-6237-4f1d-87e3-85d45f4046cd.png)
при не валидных данных полетел запрос

2023-03-26 23:40 UTC, SergeyGlazun commented on cypress.config.ts
> +        experimentalSessionAndOrigin: true,
![image](https://user-images.githubusercontent.com/70904466/227811223-ee48d0ff-9a49-4257-a2be-e6b979f1feca.png)
забронировал книгу а бронь истекла сразу

2023-03-26 23:40 UTC, SergeyGlazun commented on cypress.config.ts
>          screenshotsFolder: "cypress/report/screenshots",
![image](https://user-images.githubusercontent.com/70904466/227811247-d0399d88-a52f-409a-8dc3-0e9dc3e84b0c.png)
тут тоже бага

2023-03-26 23:40 UTC, SergeyGlazun commented on cypress.config.ts
>          screenshotsFolder: "cypress/report/screenshots",
только перешел а уже ошибка

2023-03-26 23:40 UTC, SergeyGlazun commented on cypress.config.ts
>          reporter: "mochawesome",
![image](https://user-images.githubusercontent.com/70904466/227811372-982c3b2f-8c60-437a-a36f-f717abfb97c2.png)
вот теперь вижу но я перебронироавл другую книгу на след день (28 число) бага на 27 числе

2023-03-26 23:40 UTC, SergeyGlazun commented on cypress.config.ts
>          reporterOptions: {
![image](https://user-images.githubusercontent.com/70904466/227811492-b003db8c-b0ed-47ca-bee9-aba6bc56080c.png)
не по дизайну скорее всего

2023-03-26 23:40 UTC, SergeyGlazun commented on src/header/header.module.scss
>                  margin-left: 8px;
![image](https://user-images.githubusercontent.com/70904466/227811531-73616d15-68b6-4ff3-b1df-11a29a03b99e.png)
поломалась верстка при растяжке с мобильной версии

2023-03-26 23:40 UTC, SergeyGlazun commented on src/header/header.module.scss
>                  height: 68px;
![image](https://user-images.githubusercontent.com/70904466/227811588-38ac2a20-3b89-4570-bbdb-715c24e377c9.png)
тут котик вроде должен стоять по макету

2023-03-26 23:40 UTC, SergeyGlazun commented on src/header/header.module.scss
>              }
![image](https://user-images.githubusercontent.com/70904466/227811686-865b8aee-1f2b-47c9-96e5-54b7a50e87e5.png)
бага отоброжения при закрытии списка

2023-03-26 23:40 UTC, SergeyGlazun commented on src/header/header.module.scss
>      }
![image](https://user-images.githubusercontent.com/70904466/227811717-5c927d18-8504-4667-8241-df689f45e332.png)
скролл

2023-03-26 23:40 UTC, SergeyGlazun commented on src/header/header.tsx
>  import React, {useState} from 'react';
![image](https://user-images.githubusercontent.com/70904466/227811758-32e00dd4-707f-4e81-8abf-500e27ecb0e8.png)
не видно часть контента

2023-03-26 23:40 UTC, SergeyGlazun commented on src/header/header.tsx
> +import {Link, NavLink, useLocation} from 'react-router-dom';
![image](https://user-images.githubusercontent.com/70904466/227811786-03a1b529-cf77-4521-aa19-1e7a15dfabfd.png)
тени вроде нет в макете на хедере

2023-03-26 23:40 UTC, SergeyGlazun commented on src/header/header.tsx
> -import logoClevertec from '../assets/logoCleverland.svg';
![image](https://user-images.githubusercontent.com/70904466/227811870-2dc0e470-bb47-4033-96f4-0d302110a976.png)
после открытия бургера едет верстка

2023-03-26 23:40 UTC, SergeyGlazun commented on src/header/header.tsx
> +import logoClevertec from '../assets/header/logoCleverland.svg';
![image](https://user-images.githubusercontent.com/70904466/227811957-bbf89037-7ab7-462f-b77c-53883a104857.png)
после поиска по символам и переключений баг отображения выбраны все книги поиск пуст и токо 4

2023-03-27 02:34 UTC, KaPuTaH-UluTka commented on src/header/header.tsx
> +import logoClevertec from '../assets/header/logoCleverland.svg';
Доброй ночи, спасибо за столь позднее ревью=) Вот тут я не совсем понял при каких действиях возникает проблема.
Остальные баги пофиксил, кроме двух моментов. Тень у хедера по макету появляется при открытии контекстного с профилем и выходом. Второй это логин, там все верно отрабатывает, по инструкции там валидация только на реквайред, при ошибке запроса выскакивает сообщение о неверном логине и пароле, только цвет бордера неверный, но его я тоже поправил=)

2023-03-27 02:53 UTC, Rastamanby commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 98.
Количество непройденных тестов: 0.
***
**1-slider-no-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/1-slider-no-photo-1440px.png)
***
**1-slider-no-photo-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/1-slider-no-photo-320px.png)
***
**10-app-burger-menu-close-click-not-burger-menu-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/10-app-burger-menu-close-click-not-burger-menu-768px.png)
***
**11-app-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/11-app-320px.png)
***
**12-app-burger-menu-open-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/12-app-burger-menu-open-320px.png)
***
**13-app-burger-menu-close-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/13-app-burger-menu-close-320px.png)
***
**14-app-burger-menu-close-click-not-burger-menu-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/14-app-burger-menu-close-click-not-burger-menu-320px.png)
***
**15-1440-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/15-1440-profile-page.png)
***
**16-768-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/16-768-profile-page.png)
***
**17-320-profile-page.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/17-320-profile-page.png)
***
**18-profile-avatar-before.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/18-profile-avatar-before.png)
***
**19-profile-avatar-after.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/19-profile-avatar-after.png)
***
**2-slider-one-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/2-slider-one-photo-1440px.png)
***
**2-slider-one-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/2-slider-one-photo-768px.png)
***
**20-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/20-1440-profile-empty-card.png)
***
**21-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/21-1440-profile-empty-card.png)
***
**22-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/22-1440-profile-empty-card.png)
***
**23-1440-profile-expider-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/23-1440-profile-expider-card.png)
***
**24-1440-profile-empty-card.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/24-1440-profile-empty-card.png)
***
**25-1440-profile-history.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/25-1440-profile-history.png)
***
**3-slider-more-two-photo-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/3-slider-more-two-photo-1440px.png)
***
**3-slider-more-two-photo-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/3-slider-more-two-photo-768px.png)
***
**4-slider-before-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/4-slider-before-1440px.png)
***
**4-slider-before-320px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/4-slider-before-320px.png)
***
**4-slider-before-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/4-slider-before-768px.png)
***
**5-slider-after-1440px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/5-slider-after-1440px.png)
***
**6-app-1440.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/6-app-1440.png)
***
**7-app-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/7-app-768px.png)
***
**8-app-burger-menu-open-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/8-app-burger-menu-open-768px.png)
***
**9-app -burger-menu-close-768px.png**
![Скриншот автотестов](https://static.cleverland.by/media/sprint1/KaPuTaH-UluTka/1679885607/9-app%20-burger-menu-close-768px.png)

2023-03-27 06:32 UTC, SergeyGlazun approved these changes

2023-03-27 09:30 UTC, ValadzkoAliaksei approved these changes

2023-03-27 11:41 UTC, merged